In [ ]:
#exp 15
#DATA NORMALISATION AND DATA TYPE CONVERSION
#PART-A
#RIYA RAVI NATEKAR
#25070123093

In [ ]:
import pandas as pd
import numpy as np

data = {
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price':[55000,20000,30000,2000,8000,45000],
'Units_Sold':[25,60,35,80,50,15],
'Discount':[10,15,12,20,18,8]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
#min max normalisation
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())


print(df[['Product','Price','Price_MinMax']])

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [ ]:
#min max normalisation
df['Discount_MinMax'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())


print(df[['Product','Price','Discount_MinMax']])

      Product  Price  Discount_MinMax
0      Laptop  55000         0.166667
1      Mobile  20000         0.583333
2      Tablet  30000         0.333333
3  Headphones   2000         1.000000
4  Smartwatch   8000         0.833333
5      Camera  45000         0.000000

In [ ]:
#normalise multiple coloumns
cols = ['Price','Units_Sold','Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print(df_norm)

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
#2. Z-score Normalisation
df['Price_Zscore'] = (df['Price'] - df['Price'].mean()) / df['Price'].std()
print(df[['Product','Units_Sold','Price_Zscore']])

      Product  Units_Sold  Price_Zscore
0      Laptop          25      1.365931
1      Mobile          60     -0.321396
2      Tablet          35      0.160698
3  Headphones          80     -1.189164
4  Smartwatch          50     -0.899908
5      Camera          15      0.883838

In [ ]:
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print(df[['Product','Units_Sold','Units_Zscore']])

      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [ ]:
df['Discount_Zscore'] = (df['Discount'] - df['Discount'].mean()) / df['Discount'].std()
print(df[['Product','Units_Sold','Discount_Zscore']])

      Product  Units_Sold  Discount_Zscore
0      Laptop          25        -0.821638
1      Mobile          60         0.250064
2      Tablet          35        -0.392957
3  Headphones          80         1.321766
4  Smartwatch          50         0.893085
5      Camera          15        -1.250319

In [ ]:
#normalise z scoore
cols = ['Price','Units_Sold','Discount']
df_zscore = (df[cols] - df[cols].mean()) / df[cols].std()
print(df_zscore)

      Price  Units_Sold  Discount
0  1.365931   -0.799885 -0.821638
1 -0.321396    0.660775  0.250064
2  0.160698   -0.382554 -0.392957
3 -1.189164    1.495437  1.321766
4 -0.899908    0.243443  0.893085
5  0.883838   -1.217216 -1.250319

In [ ]:
# 3. Decimal Scaling
df['Price_Decimal'] = df['Price'] / 100000
print(df[['Product','Price','Price_Decimal']])

      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [ ]:
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df = pd.DataFrame(data)
print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
#method1 : LABEL ENCODER
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Customer_Gender_Encoded']=le.fit_transform(df['Customer_Gender'])
display(df)

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Customer_Gender_Encoded
0,101,Male,UPI,Electronics,Pune,4500,1
1,102,Female,Credit Card,Clothing,Mumbai,2300,0
2,103,Female,Debit Card,Home,Delhi,3200,0
3,104,Male,COD,Electronics,Bangalore,5200,1
4,105,Female,UPI,Beauty,Pune,1800,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1

In [ ]:
#method 2 : one-hot encoding
df_encoded = pd.get_dummies(df, columns=['Payment_Method'])
display(df_encoded)

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Customer_Gender_Encoded,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,False,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,False,True,False,False
2,103,Female,Home,Delhi,3200,0,False,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,True,False,False,False
4,105,Female,Beauty,Pune,1800,0,False,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,False,False,True,False

In [ ]:
#encoding multiple coloumns
df_multi = pd.get_dummies(df, columns=['Product_Category','City'])
display(df_multi)

,Order_ID,Customer_Gender,Payment_Method,Order_Value,Customer_Gender_Encoded,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,UPI,4500,1,False,False,True,False,False,False,False,False,True
1,102,Female,Credit Card,2300,0,False,True,False,False,False,False,False,True,False
2,103,Female,Debit Card,3200,0,False,False,False,True,False,True,False,False,False
3,104,Male,COD,5200,1,False,False,True,False,True,False,False,False,False
4,105,Female,UPI,1800,0,True,False,False,False,False,False,False,False,True
5,106,Male,Debit Card,4100,1,False,False,True,False,False,False,True,False,False

In [ ]:
#method 3 : dummy encoding (Drop first)
df_dummy = pd.get_dummies(df, columns=['Payment_Method'], drop_first=True)
df_dummy

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Customer_Gender_Encoded,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,True,False,False
2,103,Female,Home,Delhi,3200,0,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,False,False,False
4,105,Female,Beauty,Pune,1800,0,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,False,True,False